site_name: "Python Project-based Based Guide"
nav:
  - 'Guess the Word': 
    - p_guess_the_word.md
  - 'Calculator':
    - p_calculator.md
  - 'Parcel Check':
    - p_parcel_check.md
  - 'ATM Machine':
    - p_atm_machine.md

theme: 
  name: readthedocs
  collapse_navigation: True

plugins:
  - mkdocs-video

markdown_extensions:
  - attr_list

extra_css:
  - assets/css/custom.css