site_name: "Python Project-based Based Guide"
nav:
  - 'Setup':
    - setup_onlinepy.md
    - setup_replit.md
    - setup_vscode.md
  - 'Standard Method of Algorithm':
    - basic_1_totalling.md
    - basic_2_counting.md
    - basic_3_max_min_average.md
    - basic_4_linear_search.md
    - basic_5_bubble_sort.md
  - 'Projects':
      - p_guess_the_number.md
      - p_guess_the_word.md
      - p_calculator.md
      - p_parcel_check.md
      - p_atm_machine.md
      - p_insult_generator.md

theme: 
  name: readthedocs
  collapse_navigation: True

plugins:
  - mkdocs-video

markdown_extensions:
  - attr_list

extra_css:
  - assets/css/custom.css